### ISSUE TITLE
[Ticket][PMT] [Investigation] Investigate Twilio Verification for HDG

### ISSUE THREAD

**Issue by mgupta8143** [GTBitsOfGood/hdg-chatbot#25]
## Nonprofit/Project Description
An Azure Functions (FaaS) Serverless WhatsApp/SMS chatbot that leverages the Twilio API and a MongoDB backend to guide users through educational modules created by Health and Development in Guatemala (HDG), an Emory-based organization.

## Ticket Description
Recently, Siri and Manu met with HDG to talk about an issue they were having with their usage of Twilio, an API that this project uses to send mass messages on WhatsApp. Unfortunately, due to the fact that HDG is a non-profit, they said they could not get verified on Facebook Business which is needed to get verified on Twilio and use the product. 

Additional Information: The NP are supposed to upload spreadsheets to the application that encode information about how the WhatsApp chatbot should flow through different messages. 

We would like to investigate how we can resolve the issue. Note that, because this is a non-profit, they can no get verified on Facebook Business because they don't have any official tax forms. This issue is more of an investigation issue and will require communication with former BOG members potentially about how they were able to get the Twilio API working and verified for them. 

Refer to [this](https://docs.google.com/document/d/1xvvumE_-8aaKl98BQVoZ7aZCwZNdPwtWM0bcmPrh2R8/edit) for more information. 

## Acceptance Criteria
- [ ] Investigate how the NP can get verified on Twilio and document the steps below. 

## Other Notes
* Ask Manu or Jay for any help!
* Make sure to communicate with other BoG members if needed

**Comment by ananyag0** [comment]
Based on [this](https://www.facebook.com/business/help/159334372093366) information, instead of submitting official tax forms, HDG can submit the Articles of Incorporation for their NP as the document Facebook Business uses for verification. 
![Image](https://user-images.githubusercontent.com/108382979/221245500-3a9f246e-9eaa-4aa1-b03b-7b88ad52a75b.png)

To make sure verification is successful, based on [this](https://repozix.com/blog/facebook-verification/), HDG must make sure that 

- Their website domain is verified
- There is a Facebook pixel on their website
- All the admins have 2-factor authentication enabled*
-  Admins must have verified their identities (admins must ID's for approval on their individual Facebook accounts) 
Important since FB deletes IDs after 1 month
- Facebook page has address and phone number, which matches the address and phone number on the Articles of Incorporation

Additionally, ensure that none of [these](https://www.facebook.com/business/help/2342133782492969?id=180505742745347) are problems preventing verification. From there, the usual steps outlined [here](https://www.twilio.com/docs/whatsapp/api) should be followed. 

Using the Articles of Incorporation might work, but after a lot of investigation, if this doesn't work, officially there doesn't seem to be another way around being an LLC. In 2020, WhatsApp changed settings such that FB Business verification is needed for access to the Twilio Whatsapp API. According to the documentation [here](https://www.twilio.com/docs/whatsapp/tutorial/whatsapp-business-account#:~:text=Any%20business%20that%20can%20complete%20Business%20Verification%20on%20the%20Meta%20Business%20Manager%20can%20have%20a%20WhatsApp%20Business%20Account.), being a registered LLC is required to get Facebook Business verification, and having Facebook Business verification is the only way to get access to Twilio's Whatsapp API. However, there is a separate process for non-profits to get access to Twilio's A2P 10DLC Text Messaging outlined [here](https://support.twilio.com/hc/en-us/articles/4405850570267-Nonprofit-and-Government-Guide-to-A2P-10DLC-Text-Messaging).

Twilio has a separate website for non-profits (https://twilio.org/, not the main twilio.com), and I have contacted their support to see if there is any other way to work around non-profits using Twilio for Whatsapp without a Facebook Business account - still waiting for a response (Support Ticket #11312182).
